index:
    path:     /todos
    defaults: { _controller: AppBundle:TodoController:index }
    methods: [GET]

store:
    path:     /todos
    defaults: { _controller: AppBundle:TodoController:store }
    methods: [POST]

show:
    path:     /todos/{id}
    defaults: { _controller: AppBundle:TodoController:show }
    methods: [GET]
    requirements:
        id: \d+

update:
    path:     /todos/{id}
    defaults: { _controller: AppBundle:TodoController:update }
    methods: [PUT]
    requirements:
        id: \d+

destroy:
    path:     /todos/{id}
    defaults: { _controller: AppBundle:TodoController:destroy }
    methods: [DELETE]
    requirements:
        id: \d+

CategoriesIndex:
    path:     /categories
    defaults: { _controller: AppBundle:CategoryController:index }
    methods: [GET]

store:
    path:     /categories
    defaults: { _controller: AppBundle:CategoryController:store }
    methods: [POST]

show:
    path:     /categories/{id}
    defaults: { _controller: AppBundle:CategoryController:show }
    methods: [GET]
    requirements:
        id: \d+

update:
    path:     /categories/{id}
    defaults: { _controller: AppBundle:CategoryController:update }
    methods: [PUT]
    requirements:
        id: \d+

destroy:
    path:     /categories/{id}
    defaults: { _controller: AppBundle:CategoryController:destroy }
    methods: [DELETE]
    requirements:
        id: \d+
